preprocessing

diff --git a/0x00-hello_world/0-prepocessor b/0x00-hello_world/0-prepocessor
--- a/0x00-hello_world/0-prepocessor
+++ b/0x00-hello_world/0-prepocessor
@@ -2,3 +2,9 @@
 CFILE="0-preprocessor"
 
 gcc -E $CFILE > c
+
+if [$? -ne 0 ]; then
+	echo "gcc command failed"
+else
+	echo "gcc command succeeded"
+fi
